"""add parsed_releases table

Revision ID: 3695c15c7688
Revises: 
Create Date: 2026-04-04 17:35:56.105233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3695c15c7688'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsed_releases',
    sa.Column('raw_title', sa.String(), nullable=False),
    sa.Column('parsed_title', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episode', sa.Integer(), nullable=True),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('resolution', sa.String(), nullable=True),
    sa.Column('release_group', sa.String(), nullable=True),
    sa.Column('is_proper', sa.Boolean(), nullable=False),
    sa.Column('is_repack', sa.Boolean(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('parse_method', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parsed_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parsed_releases_raw_title'), ['raw_title'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parsed_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parsed_releases_raw_title'))

    op.drop_table('parsed_releases')
    # ### end Alembic commands ###
